version: '3.9'

services:

  docker-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
    ports:
      - 3307:3306

  account:
    image: bank-system/account:latest
    mem_limit: 700m
    ports:
      - "1001:1001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/bank_system_mc?autoReconnect=true&useSSL=false
      depends_on:
        - docker-mysql